spring:
    security:
      oauth2:
        resourceserver:
            jwt:
                issuer-uri: ${JWT_ISSUER_URI:http://localhost:4080/auth/realms/mydomain}
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${JDBC_URL:jdbc:postgresql://localhost:5432/todo}
        hikari:
            password: ${DB_PASSWORD:postgres}
            username: ${DB_USERNAME:postgres}
            maximum-pool-size: 100
            minimum-idle: 100
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: false
                generate_statistics: false
    kafka:
        bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
        consumer:
            bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            auto-offset-reset: earliest
            properties:
              specific:
                avro:
                    reader: true
        properties:
            schema:
                registry:
                    url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}


dependencies:
    users:
        service:
            url:
                http://localhost:4080/mydomain/users/

log:
    level:
        org.springframework.web: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,mappings

application:
    kafka:
        enabled: false