spring:
    security:
      oauth2:
        resourceserver:
            jwt:
                issuer-uri: http://localhost:4080/auth/realms/mydomain
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/todo
        hikari:
            password: postgres
            username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: false
    kafka:
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            auto-offset-reset: earliest
            properties:
              specific:
                avro:
                    reader: true
        properties:
            schema.registry.url: http://localhost:8081

server:
    port: 9090

dependencies:
    users:
        service:
            url:
                http://localhost:4080/mydomain/users/

log:
    level:
        org.springframework: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus