name: Test

on:
  push:
    branches:
      - main
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Build jar
        run: ./mvnw clean package

      - name: Build docker image
        run: docker context list

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down